# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AirmassConstraint(BaseModel):
    """
    Constraint based on airmass (zenith angle) for ground-based telescopes.  Airmass affects the quality of astronomical observations. Higher airmass means more atmospheric absorption and poorer image quality. This constraint ensures observations are conducted at acceptable airmass values.  Parameters ---------- max_air_mass : float     Maximum allowed airmass. Observations with higher airmass will be constrained.     Typical values: 1.5-2.0 for good quality, up to 3.0 for some surveys.  Methods ------- __call__(time, ephemeris, coordinate)     Checks if the airmass is too high for the given coordinate and time.
    """ # noqa: E501
    short_name: Optional[StrictStr] = 'Airmass'
    name: Optional[StrictStr] = 'Airmass Limit'
    max_air_mass: Optional[Union[StrictFloat, StrictInt]] = Field(default=2.0, description="Maximum allowed airmass for observations")
    __properties: ClassVar[List[str]] = ["short_name", "name", "max_air_mass"]

    @field_validator('short_name')
    def short_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Airmass']):
            raise ValueError("must be one of enum values ('Airmass')")
        return value

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Airmass Limit']):
            raise ValueError("must be one of enum values ('Airmass Limit')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AirmassConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AirmassConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "short_name": obj.get("short_name") if obj.get("short_name") is not None else 'Airmass',
            "name": obj.get("name") if obj.get("name") is not None else 'Airmass Limit',
            "max_air_mass": obj.get("max_air_mass") if obj.get("max_air_mass") is not None else 2.0
        })
        return _obj


