# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class BrightStarConstraint(BaseModel):
    """
    Constraint that avoids observing too close to bright stars.  Bright stars can cause detector saturation, blooming, or scattered light issues. This constraint ensures observations are conducted at sufficient angular distance from bright stars.  Parameters ---------- min_separation : float     Minimum angular separation (degrees) required from bright stars.     Observations closer than this to bright stars will be constrained. magnitude_limit : float     Magnitude limit for bright stars to avoid. Stars brighter than this     magnitude will be considered for avoidance. Default is 6.0 (naked eye visible).  Methods ------- __call__(time, ephemeris, coordinate)     Checks if the coordinate is too close to any bright star.
    """ # noqa: E501
    short_name: Optional[StrictStr] = 'Bright Star'
    name: Optional[StrictStr] = 'Bright Star Avoidance'
    min_separation: Optional[Union[StrictFloat, StrictInt]] = Field(default=5.0, description="Minimum angular separation (degrees) from bright stars")
    magnitude_limit: Optional[Union[StrictFloat, StrictInt]] = Field(default=6.0, description="Magnitude limit for stars to avoid (brighter than this)")
    __properties: ClassVar[List[str]] = ["short_name", "name", "min_separation", "magnitude_limit"]

    @field_validator('short_name')
    def short_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Bright Star']):
            raise ValueError("must be one of enum values ('Bright Star')")
        return value

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Bright Star Avoidance']):
            raise ValueError("must be one of enum values ('Bright Star Avoidance')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrightStarConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrightStarConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "short_name": obj.get("short_name") if obj.get("short_name") is not None else 'Bright Star',
            "name": obj.get("name") if obj.get("name") is not None else 'Bright Star Avoidance',
            "min_separation": obj.get("min_separation") if obj.get("min_separation") is not None else 5.0,
            "magnitude_limit": obj.get("magnitude_limit") if obj.get("magnitude_limit") is not None else 6.0
        })
        return _obj


