# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BrokerAlertStatus(str, Enum):
    """
    BrokerAlertStatus
    """

    """
    allowed enum values
    """
    INITIAL = 'initial'
    PRELIMINARY = 'preliminary'
    CONFIRMED = 'confirmed'
    RETRACTED = 'retracted'
    EARLY_WARNING = 'early_warning'
    CLASSIFIED = 'classified'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BrokerAlertStatus from a JSON string"""
        return cls(json.loads(json_str))


