# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from across.sdk.v1.models.broker_alert_data_source import BrokerAlertDataSource
from across.sdk.v1.models.broker_alert_status import BrokerAlertStatus
from typing import Optional, Set
from typing_extensions import Self

class BrokerAlert(BaseModel):
    """
    A Pydantic model class representing a BrokerAlert in the ACROSS system.  Parameters ---------- id : UUID     Broker alert id status : BrokerAlertStatus     Status of the alert broker_name : str     Name of the broker issuing the alert data_source : BrokerAlertDataSource     Source of the alert external_event_id: str     External name of the BrokerEvent associated with this alert broker_event_id: uuid     ID of the associated BrokerEvent in the ACROSS system broker_received_on: datetime     Datetime the broker received this alert payload: dict     The alert payload, containing unstructured data about the event
    """ # noqa: E501
    id: StrictStr
    status: BrokerAlertStatus
    broker_name: StrictStr
    data_source: BrokerAlertDataSource
    external_event_id: StrictStr
    broker_event_id: StrictStr
    broker_received_on: datetime
    payload: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["id", "status", "broker_name", "data_source", "external_event_id", "broker_event_id", "broker_received_on", "payload"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrokerAlert from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrokerAlert from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "broker_name": obj.get("broker_name"),
            "data_source": obj.get("data_source"),
            "external_event_id": obj.get("external_event_id"),
            "broker_event_id": obj.get("broker_event_id"),
            "broker_received_on": obj.get("broker_received_on"),
            "payload": obj.get("payload")
        })
        return _obj


