# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from across.sdk.v1.models.broker_alert import BrokerAlert
from across.sdk.v1.models.broker_event_type import BrokerEventType
from across.sdk.v1.models.localization import Localization
from typing import Optional, Set
from typing_extensions import Self

class BrokerEvent(BaseModel):
    """
    A Pydantic model class representing a BrokerEvent in the ACROSS system.  Parameters ---------- localizations : list[Localization]     Localizations associated with this event alerts : list[BrokerAlert]     Alerts associated with this event  Methods -------- from_orm:     Converts ORM BrokerEvent model to a schemas.BrokerEvent object
    """ # noqa: E501
    id: StrictStr
    event_datetime: datetime
    type: BrokerEventType
    name: StrictStr
    localizations: List[Localization]
    broker_alerts: List[BrokerAlert]
    __properties: ClassVar[List[str]] = ["id", "event_datetime", "type", "name", "localizations", "broker_alerts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrokerEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in localizations (list)
        _items = []
        if self.localizations:
            for _item_localizations in self.localizations:
                if _item_localizations:
                    _items.append(_item_localizations.to_dict())
            _dict['localizations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in broker_alerts (list)
        _items = []
        if self.broker_alerts:
            for _item_broker_alerts in self.broker_alerts:
                if _item_broker_alerts:
                    _items.append(_item_broker_alerts.to_dict())
            _dict['broker_alerts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrokerEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "event_datetime": obj.get("event_datetime"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "localizations": [Localization.from_dict(_item) for _item in obj["localizations"]] if obj.get("localizations") is not None else None,
            "broker_alerts": [BrokerAlert.from_dict(_item) for _item in obj["broker_alerts"]] if obj.get("broker_alerts") is not None else None
        })
        return _obj


