# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from across.sdk.v1.models.twilight_type import TwilightType
from typing import Optional, Set
from typing_extensions import Self

class DaytimeConstraint(BaseModel):
    """
    Constraint that avoids daytime observations based on twilight definitions.  For ground-based telescopes, daytime is defined by the Sun's position relative to the horizon. Different twilight types provide different levels of darkness.  For space-based telescopes, daytime refers to periods when the spacecraft is in direct sunlight (requires appropriate ephemeris data).  The telescope type (ground vs space) is automatically detected based on the ephemeris type: GroundEphemeris for ground-based, all others for space-based.  Parameters ---------- twilight_type : TwilightType     The type of twilight to use for defining daytime boundaries.     - 'astronomical': Sun 12-18° below horizon (default)     - 'nautical': Sun 6-12° below horizon     - 'civil': Sun 0-6° below horizon     - 'day': Sun above horizon  Methods ------- __call__(time, ephemeris, coordinate)     Checks if the observation time qualifies as daytime for the given constraints.
    """ # noqa: E501
    short_name: Optional[StrictStr] = 'Daytime'
    name: Optional[StrictStr] = 'Daytime Avoidance'
    twilight_type: Optional[TwilightType] = Field(default=None, description="Type of twilight defining daytime boundaries")
    __properties: ClassVar[List[str]] = ["short_name", "name", "twilight_type"]

    @field_validator('short_name')
    def short_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Daytime']):
            raise ValueError("must be one of enum values ('Daytime')")
        return value

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Daytime Avoidance']):
            raise ValueError("must be one of enum values ('Daytime Avoidance')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DaytimeConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DaytimeConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "short_name": obj.get("short_name") if obj.get("short_name") is not None else 'Daytime',
            "name": obj.get("name") if obj.get("name") is not None else 'Daytime Avoidance',
            "twilight_type": obj.get("twilight_type")
        })
        return _obj


