# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DepthUnit(str, Enum):
    """
    DepthUnit
    """

    """
    allowed enum values
    """
    AB_MAG = 'ab_mag'
    VEGA_MAG = 'vega_mag'
    FLUX_ERG = 'flux_erg'
    FLUX_JY = 'flux_jy'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DepthUnit from a JSON string"""
        return cls(json.loads(json_str))


