# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EnergyUnit(str, Enum):
    """
    Enum to represent the bandpass energy types
    """

    """
    allowed enum values
    """
    EV = 'eV'
    KEV = 'keV'
    MEV = 'MeV'
    GEV = 'GeV'
    TEV = 'TeV'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EnergyUnit from a JSON string"""
        return cls(json.loads(json_str))


