# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class GalacticBulgeConstraint(BaseModel):
    """
    Constraint that avoids observing too close to the Galactic Bulge.  The Galactic Bulge is a crowded region with extremely high stellar density, making it difficult to observe individual sources. This constraint ensures observations avoid this region.  Parameters ---------- min_separation : float     Minimum angular separation (degrees) required from the Galactic Bulge.     Observations closer than this will be constrained.  Methods ------- __call__(time, ephemeris, coordinate)     Checks if the coordinate is too close to the Galactic Bulge.
    """ # noqa: E501
    short_name: Optional[StrictStr] = 'Galactic Bulge'
    name: Optional[StrictStr] = 'Galactic Bulge Avoidance'
    min_separation: Optional[Union[Annotated[float, Field(le=180.0, strict=True)], Annotated[int, Field(le=180, strict=True)]]] = Field(default=10.0, description="Minimum angular separation (degrees) from Galactic Bulge")
    __properties: ClassVar[List[str]] = ["short_name", "name", "min_separation"]

    @field_validator('short_name')
    def short_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Galactic Bulge']):
            raise ValueError("must be one of enum values ('Galactic Bulge')")
        return value

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Galactic Bulge Avoidance']):
            raise ValueError("must be one of enum values ('Galactic Bulge Avoidance')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GalacticBulgeConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GalacticBulgeConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "short_name": obj.get("short_name") if obj.get("short_name") is not None else 'Galactic Bulge',
            "name": obj.get("name") if obj.get("name") is not None else 'Galactic Bulge Avoidance',
            "min_separation": obj.get("min_separation") if obj.get("min_separation") is not None else 10.0
        })
        return _obj


