# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from across.sdk.v1.models.localization_contour_base import LocalizationContourBase
from typing import Optional, Set
from typing_extensions import Self

class Localization(BaseModel):
    """
    A Pydantic model class representing a Localization in the ACROSS system. Inherits from LocalizationBase  Parameters ---------- id : UUID     Localization id broker_alert_id : UUID     ID of the alert associated with this localization broker_event_id: UUID     ID of the event associated with this localization
    """ # noqa: E501
    ra: Optional[Union[StrictFloat, StrictInt]] = None
    dec: Optional[Union[StrictFloat, StrictInt]] = None
    contours: Optional[List[LocalizationContourBase]] = None
    probability_enclosed: Optional[Union[StrictFloat, StrictInt]] = None
    id: StrictStr
    broker_event_id: StrictStr
    broker_alert_id: StrictStr
    __properties: ClassVar[List[str]] = ["ra", "dec", "contours", "probability_enclosed", "id", "broker_event_id", "broker_alert_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Localization from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in contours (list)
        _items = []
        if self.contours:
            for _item_contours in self.contours:
                if _item_contours:
                    _items.append(_item_contours.to_dict())
            _dict['contours'] = _items
        # set to None if ra (nullable) is None
        # and model_fields_set contains the field
        if self.ra is None and "ra" in self.model_fields_set:
            _dict['ra'] = None

        # set to None if dec (nullable) is None
        # and model_fields_set contains the field
        if self.dec is None and "dec" in self.model_fields_set:
            _dict['dec'] = None

        # set to None if contours (nullable) is None
        # and model_fields_set contains the field
        if self.contours is None and "contours" in self.model_fields_set:
            _dict['contours'] = None

        # set to None if probability_enclosed (nullable) is None
        # and model_fields_set contains the field
        if self.probability_enclosed is None and "probability_enclosed" in self.model_fields_set:
            _dict['probability_enclosed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Localization from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ra": obj.get("ra"),
            "dec": obj.get("dec"),
            "contours": [LocalizationContourBase.from_dict(_item) for _item in obj["contours"]] if obj.get("contours") is not None else None,
            "probability_enclosed": obj.get("probability_enclosed"),
            "id": obj.get("id"),
            "broker_event_id": obj.get("broker_event_id"),
            "broker_alert_id": obj.get("broker_alert_id")
        })
        return _obj


