# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from across.sdk.v1.models.point import Point
from typing import Optional, Set
from typing_extensions import Self

class ObservationFootprint(BaseModel):
    """
    A Pydantic model class representing a created ObservationFootprint  Notes ----- Inherits from ObservationFootprintBase  Methods ------- from_orm(obj: ObservationFootprintModel) -> ObservationFootprint     Static method that instantiates this class from an observation footprint database record
    """ # noqa: E501
    polygon: List[Point]
    id: StrictStr
    observation_id: StrictStr
    __properties: ClassVar[List[str]] = ["polygon", "id", "observation_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ObservationFootprint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in polygon (list)
        _items = []
        if self.polygon:
            for _item_polygon in self.polygon:
                if _item_polygon:
                    _items.append(_item_polygon.to_dict())
            _dict['polygon'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ObservationFootprint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "polygon": [Point.from_dict(_item) for _item in obj["polygon"]] if obj.get("polygon") is not None else None,
            "id": obj.get("id"),
            "observation_id": obj.get("observation_id")
        })
        return _obj


