# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ObservationStrategy(str, Enum):
    """
    ObservationStrategy
    """

    """
    allowed enum values
    """
    POINTED = 'pointed'
    SURVEY = 'survey'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ObservationStrategy from a JSON string"""
        return cls(json.loads(json_str))


