# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from across.sdk.v1.models.pointing import Pointing
from typing import Optional, Set
from typing_extensions import Self

class PointingConstraint(BaseModel):
    """
    Footprint based pointing constraint. A Pointing is defined as a Footprint with a start and end time. This constraint will calculate whether a target was within any set of pointings.  Attributes ---------- pointings     List of Pointing objects. start_time     AstropyDateTime defining the start of the pointing end_time     AstropyDateTime defining the end of the pointing
    """ # noqa: E501
    short_name: Optional[StrictStr] = 'Pointing'
    name: Optional[StrictStr] = 'Pointing'
    pointings: List[Pointing]
    __properties: ClassVar[List[str]] = ["short_name", "name", "pointings"]

    @field_validator('short_name')
    def short_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Pointing']):
            raise ValueError("must be one of enum values ('Pointing')")
        return value

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Pointing']):
            raise ValueError("must be one of enum values ('Pointing')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PointingConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in pointings (list)
        _items = []
        if self.pointings:
            for _item_pointings in self.pointings:
                if _item_pointings:
                    _items.append(_item_pointings.to_dict())
            _dict['pointings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PointingConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "short_name": obj.get("short_name") if obj.get("short_name") is not None else 'Pointing',
            "name": obj.get("name") if obj.get("name") is not None else 'Pointing',
            "pointings": [Pointing.from_dict(_item) for _item in obj["pointings"]] if obj.get("pointings") is not None else None
        })
        return _obj


