# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from across.sdk.v1.models.solar_system_constraint_bodies_inner import SolarSystemConstraintBodiesInner
from typing import Optional, Set
from typing_extensions import Self

class SolarSystemConstraint(BaseModel):
    """
    Constraint that avoids observing too close to bright Solar System objects.  Planets and other bright Solar System objects can contaminate observations or cause detector issues. This constraint ensures observations avoid these objects by maintaining sufficient angular separation.  Parameters ---------- min_separation : float     Minimum angular separation (degrees) required from Solar System objects.     Observations closer than this will be constrained. bodies : list[str]     List of Solar System bodies to avoid. Defaults to major planets.     Options include: 'mercury', 'venus', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune'.  Methods ------- __call__(time, ephemeris, coordinate)     Checks if the coordinate is too close to any Solar System object.
    """ # noqa: E501
    short_name: Optional[StrictStr] = 'Solar System'
    name: Optional[StrictStr] = 'Solar System Object Avoidance'
    min_separation: Optional[Union[StrictFloat, StrictInt]] = Field(default=10.0, description="Minimum angular separation (degrees) from Solar System objects")
    max_magnitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=5.0, description="Maximum apparent magnitude of Solar System objects to consider")
    bodies: Optional[List[SolarSystemConstraintBodiesInner]] = Field(default=None, description="List of Solar System bodies to avoid")
    __properties: ClassVar[List[str]] = ["short_name", "name", "min_separation", "max_magnitude", "bodies"]

    @field_validator('short_name')
    def short_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Solar System']):
            raise ValueError("must be one of enum values ('Solar System')")
        return value

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Solar System Object Avoidance']):
            raise ValueError("must be one of enum values ('Solar System Object Avoidance')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SolarSystemConstraint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bodies (list)
        _items = []
        if self.bodies:
            for _item_bodies in self.bodies:
                if _item_bodies:
                    _items.append(_item_bodies.to_dict())
            _dict['bodies'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SolarSystemConstraint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "short_name": obj.get("short_name") if obj.get("short_name") is not None else 'Solar System',
            "name": obj.get("name") if obj.get("name") is not None else 'Solar System Object Avoidance',
            "min_separation": obj.get("min_separation") if obj.get("min_separation") is not None else 10.0,
            "max_magnitude": obj.get("max_magnitude") if obj.get("max_magnitude") is not None else 5.0,
            "bodies": [SolarSystemConstraintBodiesInner.from_dict(_item) for _item in obj["bodies"]] if obj.get("bodies") is not None else None
        })
        return _obj


