# coding: utf-8

"""
    ACROSS Server

    Server providing tools and utilities for various NASA missions to aid in coordination of large observation efforts.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from across.sdk.v1.models.earth_angle import EarthAngle
from across.sdk.v1.models.galactic_bulge_separation import GalacticBulgeSeparation
from across.sdk.v1.models.moon_angle import MoonAngle
from across.sdk.v1.models.sun_altitude import SunAltitude
from across.sdk.v1.models.sun_angle import SunAngle
from across.sdk.v1.models.visibility_computed_values_body_separation_value import VisibilityComputedValuesBodySeparationValue
from typing import Optional, Set
from typing_extensions import Self

class VisibilityComputedValues(BaseModel):
    """
    A class to hold computed values used in constraint calculations.  Attributes ---------- sun_angle     Angular distance between the Sun and the target coordinate. moon_angle     Angular distance between the Moon and the target coordinate. earth_angle     Angular distance between the Earth limb and the target coordinate. alt_az     Altitude-azimuth coordinates of the target from the observatory.
    """ # noqa: E501
    sun_angle: Optional[SunAngle] = None
    moon_angle: Optional[MoonAngle] = None
    earth_angle: Optional[EarthAngle] = None
    alt_az: Optional[List[Dict[str, Optional[Union[StrictFloat, StrictInt]]]]] = None
    air_mass: Optional[List[Any]] = None
    sun_altitude: Optional[SunAltitude] = None
    body_separation: Optional[Dict[str, VisibilityComputedValuesBodySeparationValue]] = None
    body_coordinates: Optional[Dict[str, List[Dict[str, Union[StrictFloat, StrictInt]]]]] = None
    body_magnitude: Optional[Dict[str, List[Any]]] = None
    galactic_bulge_separation: Optional[GalacticBulgeSeparation] = None
    __properties: ClassVar[List[str]] = ["sun_angle", "moon_angle", "earth_angle", "alt_az", "air_mass", "sun_altitude", "body_separation", "body_coordinates", "body_magnitude", "galactic_bulge_separation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VisibilityComputedValues from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sun_angle
        if self.sun_angle:
            _dict['sun_angle'] = self.sun_angle.to_dict()
        # override the default output from pydantic by calling `to_dict()` of moon_angle
        if self.moon_angle:
            _dict['moon_angle'] = self.moon_angle.to_dict()
        # override the default output from pydantic by calling `to_dict()` of earth_angle
        if self.earth_angle:
            _dict['earth_angle'] = self.earth_angle.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sun_altitude
        if self.sun_altitude:
            _dict['sun_altitude'] = self.sun_altitude.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in body_separation (dict)
        _field_dict = {}
        if self.body_separation:
            for _key_body_separation in self.body_separation:
                if self.body_separation[_key_body_separation]:
                    _field_dict[_key_body_separation] = self.body_separation[_key_body_separation].to_dict()
            _dict['body_separation'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of galactic_bulge_separation
        if self.galactic_bulge_separation:
            _dict['galactic_bulge_separation'] = self.galactic_bulge_separation.to_dict()
        # set to None if sun_angle (nullable) is None
        # and model_fields_set contains the field
        if self.sun_angle is None and "sun_angle" in self.model_fields_set:
            _dict['sun_angle'] = None

        # set to None if moon_angle (nullable) is None
        # and model_fields_set contains the field
        if self.moon_angle is None and "moon_angle" in self.model_fields_set:
            _dict['moon_angle'] = None

        # set to None if earth_angle (nullable) is None
        # and model_fields_set contains the field
        if self.earth_angle is None and "earth_angle" in self.model_fields_set:
            _dict['earth_angle'] = None

        # set to None if alt_az (nullable) is None
        # and model_fields_set contains the field
        if self.alt_az is None and "alt_az" in self.model_fields_set:
            _dict['alt_az'] = None

        # set to None if air_mass (nullable) is None
        # and model_fields_set contains the field
        if self.air_mass is None and "air_mass" in self.model_fields_set:
            _dict['air_mass'] = None

        # set to None if sun_altitude (nullable) is None
        # and model_fields_set contains the field
        if self.sun_altitude is None and "sun_altitude" in self.model_fields_set:
            _dict['sun_altitude'] = None

        # set to None if body_separation (nullable) is None
        # and model_fields_set contains the field
        if self.body_separation is None and "body_separation" in self.model_fields_set:
            _dict['body_separation'] = None

        # set to None if body_coordinates (nullable) is None
        # and model_fields_set contains the field
        if self.body_coordinates is None and "body_coordinates" in self.model_fields_set:
            _dict['body_coordinates'] = None

        # set to None if body_magnitude (nullable) is None
        # and model_fields_set contains the field
        if self.body_magnitude is None and "body_magnitude" in self.model_fields_set:
            _dict['body_magnitude'] = None

        # set to None if galactic_bulge_separation (nullable) is None
        # and model_fields_set contains the field
        if self.galactic_bulge_separation is None and "galactic_bulge_separation" in self.model_fields_set:
            _dict['galactic_bulge_separation'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VisibilityComputedValues from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sun_angle": SunAngle.from_dict(obj["sun_angle"]) if obj.get("sun_angle") is not None else None,
            "moon_angle": MoonAngle.from_dict(obj["moon_angle"]) if obj.get("moon_angle") is not None else None,
            "earth_angle": EarthAngle.from_dict(obj["earth_angle"]) if obj.get("earth_angle") is not None else None,
            "alt_az": obj.get("alt_az"),
            "air_mass": obj.get("air_mass"),
            "sun_altitude": SunAltitude.from_dict(obj["sun_altitude"]) if obj.get("sun_altitude") is not None else None,
            "body_separation": dict(
                (_k, VisibilityComputedValuesBodySeparationValue.from_dict(_v))
                for _k, _v in obj["body_separation"].items()
            )
            if obj.get("body_separation") is not None
            else None,
            "body_coordinates": obj.get("body_coordinates"),
            "body_magnitude": obj.get("body_magnitude"),
            "galactic_bulge_separation": GalacticBulgeSeparation.from_dict(obj["galactic_bulge_separation"]) if obj.get("galactic_bulge_separation") is not None else None
        })
        return _obj


